#Universal Variables

tenant_url = 'https://davefsandbox.us.qlikcloud.com/'
api_key = "Bearer eyJhbGciOiJFUzM4NCIsImtpZCI6IjRmMzY1YmQ3LTY3ZDkmFudElkIjoiZTN4YXBWLThyMUJmektmOUVERFFrcUt2dWE0djhHbTgiLCJqdGkiOiI0ZjM2NWJkNy02N2Q5LTRlODYtODUyNS00OGZmNjVmMDliODAiLCJhdWQiOiJxbGlrLmFwaSIsImlzcyI6InFsaWsuYXBpL2FwaS1rZXlzIiwic3ViIjoiMEdEZTduSElRREp1UmY4X25EQWJFZkozUEtoNHJXQnkifQ.ua7QBYC8cul3zJIe-sfROX_6goJhIZibeNdV1BHYyC0CCXbArOcTQUK71ZG7fz7_o2YeSL-3h93-08OWosY5svHlUWa_EGD6PF4eMjvD4RmHHL9m2NkHbfSWx4E1E_lu"
