#Universal Variables

tenant_url = 'https://davefsandbox.us.qlikcloud.com/'
api_key = "Bearer eyJhbGciOiJFUzM4NCWJUeXBlIjoidXNlciIsInRlbmFudElkIjoiZTN4YXBWLThyMUJmektmOUVERFFrcUt2dWE0djhHbTgiLCJqdGkiOiIzM2I2NGNhMi04MjY5LTQ1NWMtOWZiMy1lOThlMmJiN2Q2N2IiLCJhdWQiOiJxbGlrLmFwaSIsImlzcyI6InFsaWsuYXBpL2FwaS1rZXlzIiwic3ViIjoiMEdEZTduSElRREp1UmY4X25EQWJFZkozUEtoNHJXQnkifQ.WTrpnm19yE6UX0JlnOJQXrj9jxi_JzrrrGOTRPJyTLwVpStPS7FdFRiW49snZ0vwJz_uXgUn292M7Fop4waCrZW6Po0VPqF2GAsB1elEdZeN2Ia85mxVcsoz8Z_WqlOH"
